### ISSUE TITLE
Orphaned MimirRule crashes the operator

### ISSUE THREAD

**Issue by fourstepper** [oskoperator/osko#57]
If the operator is not running while an `SLO` is deleted from the cluster (i.e. with `kubectl delete -f config/samples/openslo_v1_slo.yaml`), the operator crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x68 pc=0x10189a444]

goroutine 291 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /Users/robin.opletal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:116 +0x1a4
panic({0x1020fd9e0?, 0x10331ca90?})
        /opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/panic.go:770 +0x124
github.com/grafana/mimir/pkg/mimirtool/client.(*MimirClient).DeleteRuleGroup(0x0, {0x1023ba358, 0x1033c6a80}, {0x1018aad3a?, 0x140009ffaa8?}, {0x140008b2510, 0x21})
        /Users/robin.opletal/go/pkg/mod/github.com/grafana/mimir@v0.0.0-20231101181902-68d120862184/pkg/mimirtool/client/rules.go:46 +0x64
github.com/oskoperator/osko/internal/controller/osko.(*MimirRuleReconciler).deleteMimirRuleGroupAPI(0x140000b1ef0?, {{0x1023bddd8?, 0x14000a5b590?}, 0x14000c25046?}, {0x140008b2510?, 0x140008b2510?})
        /Users/robin.opletal/workspace/personal/osko/internal/controller/osko/mimirrule_controller.go:253 +0x60
github.com/oskoperator/osko/internal/controller/osko.(*MimirRuleReconciler).Reconcile(0x140007fec40, {0x1023ba4a8, 0x14000a5b560}, {{{0x14000c25046, 0x7}, {0x140008b2510?, 0x140009ffd48?}}})
        /Users/robin.opletal/workspace/personal/osko/internal/controller/osko/mimirrule_controller.go:82 +0x21c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1023bddd8?, {0x1023ba4a8?, 0x14000a5b560?}, {{{0x14000c25046?, 0xb?}, {0x140008b2510?, 0x0?}}})
        /Users/robin.opletal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x140001a8dc0, {0x1023ba4e0, 0x140007b2f50}, {0x10219eb40, 0x14000b0c5e0})
        /Users/robin.opletal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316 +0x2dc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x140001a8dc0, {0x1023ba4e0, 0x140007b2f50})
        /Users/robin.opletal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266 +0x198
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /Users/robin.opletal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 31
        /Users/robin.opletal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:223 +0x404
exit status 2
make: *** [run] Error 1
```

**Comment by Hy3n4** [comment]
Imo the operator is crashing, because the SLO is missing, and the MImirRule is orphaned due to a missing owner. Therefore the nil pointer dereference.
